// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZwXcXVUCcATpfqJnJ8lgcqVkpq9JuxZQ',
    appId: '1:794653707199:web:e92640d6802870f817ef0a',
    messagingSenderId: '794653707199',
    projectId: 'hisab-7e78a',
    authDomain: 'hisab-7e78a.firebaseapp.com',
    storageBucket: 'hisab-7e78a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3vffALcAv7utFf9PF23vGke9Mw34zn0',
    appId: '1:794653707199:android:4aa013b6b51d9cd617ef0a',
    messagingSenderId: '794653707199',
    projectId: 'hisab-7e78a',
    storageBucket: 'hisab-7e78a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2xUID3fTrCZDyCG_GrAOhhZEuphnxdgE',
    appId: '1:794653707199:ios:f4578672126195c417ef0a',
    messagingSenderId: '794653707199',
    projectId: 'hisab-7e78a',
    storageBucket: 'hisab-7e78a.appspot.com',
    iosBundleId: 'com.example.hisab',
  );
}
